/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetBookingAppointmentByTokenQueryResponse, GetBookingAppointmentByTokenPathParams, GetBookingAppointmentByToken404, GetBookingAppointmentByToken500 } from "../types/GetBookingAppointmentByToken.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getBookingAppointmentByToken } from "../clients/getBookingAppointmentByToken.ts";

export const getBookingAppointmentByTokenSuspenseQueryKey = (cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined) => [{ url: '/websites/booking/appointments/:cancelToken', params: {cancelToken:cancelToken} }] as const

export type GetBookingAppointmentByTokenSuspenseQueryKey = ReturnType<typeof getBookingAppointmentByTokenSuspenseQueryKey>

export function getBookingAppointmentByTokenSuspenseQueryOptions(cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingAppointmentByTokenSuspenseQueryKey(cancelToken)
        return queryOptions<GetBookingAppointmentByTokenQueryResponse, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>, GetBookingAppointmentByTokenQueryResponse, typeof queryKey>({
         enabled: !!(cancelToken),
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingAppointmentByToken(cancelToken!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Consultar marcação pelo token de cancelamento
 * {@link /websites/booking/appointments/:cancelToken}
 */
export function useGetBookingAppointmentByTokenSuspense<TData = GetBookingAppointmentByTokenQueryResponse, TQueryKey extends QueryKey = GetBookingAppointmentByTokenSuspenseQueryKey>(cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetBookingAppointmentByTokenQueryResponse, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingAppointmentByTokenSuspenseQueryKey(cancelToken)
         

         const query = useSuspenseQuery({
          ...getBookingAppointmentByTokenSuspenseQueryOptions(cancelToken, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}