/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetBookingMyAppointmentsQueryResponse, GetBookingMyAppointmentsQueryParams, GetBookingMyAppointments401, GetBookingMyAppointments403, GetBookingMyAppointments404, GetBookingMyAppointments500 } from "../types/GetBookingMyAppointments.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getBookingMyAppointments } from "../clients/getBookingMyAppointments.ts";

export const getBookingMyAppointmentsSuspenseQueryKey = (params?: GetBookingMyAppointmentsQueryParams) => [{ url: '/websites/booking/my-appointments' }, ...(params ? [params] : [])] as const

export type GetBookingMyAppointmentsSuspenseQueryKey = ReturnType<typeof getBookingMyAppointmentsSuspenseQueryKey>

export function getBookingMyAppointmentsSuspenseQueryOptions(params?: GetBookingMyAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingMyAppointmentsSuspenseQueryKey(params)
        return queryOptions<GetBookingMyAppointmentsQueryResponse, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>, GetBookingMyAppointmentsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingMyAppointments(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Marcações do cliente autenticado neste prestador
 * {@link /websites/booking/my-appointments}
 */
export function useGetBookingMyAppointmentsSuspense<TData = GetBookingMyAppointmentsQueryResponse, TQueryKey extends QueryKey = GetBookingMyAppointmentsSuspenseQueryKey>(params?: GetBookingMyAppointmentsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetBookingMyAppointmentsQueryResponse, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingMyAppointmentsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getBookingMyAppointmentsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}