/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBookingSlotsQueryResponse, GetBookingSlotsQueryParams, GetBookingSlots400, GetBookingSlots404, GetBookingSlots500 } from "../types/GetBookingSlots.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBookingSlots } from "../clients/getBookingSlots.ts";

export const getBookingSlotsQueryKey = (params: GetBookingSlotsQueryParams) => [{ url: '/websites/booking/slots' }, ...(params ? [params] : [])] as const

export type GetBookingSlotsQueryKey = ReturnType<typeof getBookingSlotsQueryKey>

export function getBookingSlotsQueryOptions(params: GetBookingSlotsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingSlotsQueryKey(params)
        return queryOptions<GetBookingSlotsQueryResponse, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>, GetBookingSlotsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingSlots(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Obter horários disponíveis para uma data e serviço
 * {@link /websites/booking/slots}
 */
export function useGetBookingSlots<TData = GetBookingSlotsQueryResponse, TQueryData = GetBookingSlotsQueryResponse, TQueryKey extends QueryKey = GetBookingSlotsQueryKey>(params: GetBookingSlotsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetBookingSlotsQueryResponse, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingSlotsQueryKey(params)
         

         const query = useQuery({
          ...getBookingSlotsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}