/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBookingAppointmentByTokenQueryResponse, GetBookingAppointmentByTokenPathParams, GetBookingAppointmentByToken404, GetBookingAppointmentByToken500 } from "../types/GetBookingAppointmentByToken.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBookingAppointmentByToken } from "../clients/getBookingAppointmentByToken.ts";

export const getBookingAppointmentByTokenQueryKey = (cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined) => [{ url: '/websites/booking/appointments/:cancelToken', params: {cancelToken:cancelToken} }] as const

export type GetBookingAppointmentByTokenQueryKey = ReturnType<typeof getBookingAppointmentByTokenQueryKey>

export function getBookingAppointmentByTokenQueryOptions(cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingAppointmentByTokenQueryKey(cancelToken)
        return queryOptions<GetBookingAppointmentByTokenQueryResponse, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>, GetBookingAppointmentByTokenQueryResponse, typeof queryKey>({
         enabled: !!(cancelToken),
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingAppointmentByToken(cancelToken!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Consultar marcação pelo token de cancelamento
 * {@link /websites/booking/appointments/:cancelToken}
 */
export function useGetBookingAppointmentByToken<TData = GetBookingAppointmentByTokenQueryResponse, TQueryData = GetBookingAppointmentByTokenQueryResponse, TQueryKey extends QueryKey = GetBookingAppointmentByTokenQueryKey>(cancelToken: GetBookingAppointmentByTokenPathParams["cancelToken"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetBookingAppointmentByTokenQueryResponse, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingAppointmentByTokenQueryKey(cancelToken)
         

         const query = useQuery({
          ...getBookingAppointmentByTokenQueryOptions(cancelToken, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetBookingAppointmentByToken404 | GetBookingAppointmentByToken500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}