/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBookingMyAppointmentsQueryResponse, GetBookingMyAppointmentsQueryParams, GetBookingMyAppointments401, GetBookingMyAppointments403, GetBookingMyAppointments404, GetBookingMyAppointments500 } from "../types/GetBookingMyAppointments.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBookingMyAppointments } from "../clients/getBookingMyAppointments.ts";

export const getBookingMyAppointmentsQueryKey = (params?: GetBookingMyAppointmentsQueryParams) => [{ url: '/websites/booking/my-appointments' }, ...(params ? [params] : [])] as const

export type GetBookingMyAppointmentsQueryKey = ReturnType<typeof getBookingMyAppointmentsQueryKey>

export function getBookingMyAppointmentsQueryOptions(params?: GetBookingMyAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingMyAppointmentsQueryKey(params)
        return queryOptions<GetBookingMyAppointmentsQueryResponse, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>, GetBookingMyAppointmentsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingMyAppointments(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Marcações do cliente autenticado neste prestador
 * {@link /websites/booking/my-appointments}
 */
export function useGetBookingMyAppointments<TData = GetBookingMyAppointmentsQueryResponse, TQueryData = GetBookingMyAppointmentsQueryResponse, TQueryKey extends QueryKey = GetBookingMyAppointmentsQueryKey>(params?: GetBookingMyAppointmentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetBookingMyAppointmentsQueryResponse, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingMyAppointmentsQueryKey(params)
         

         const query = useQuery({
          ...getBookingMyAppointmentsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}