/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetBookingSlotsQueryResponse, GetBookingSlotsQueryParams, GetBookingSlots400, GetBookingSlots404, GetBookingSlots500 } from "../types/GetBookingSlots.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getBookingSlots } from "../clients/getBookingSlots.ts";

export const getBookingSlotsSuspenseQueryKey = (params: GetBookingSlotsQueryParams) => [{ url: '/websites/booking/slots' }, ...(params ? [params] : [])] as const

export type GetBookingSlotsSuspenseQueryKey = ReturnType<typeof getBookingSlotsSuspenseQueryKey>

export function getBookingSlotsSuspenseQueryOptions(params: GetBookingSlotsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingSlotsSuspenseQueryKey(params)
        return queryOptions<GetBookingSlotsQueryResponse, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>, GetBookingSlotsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingSlots(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Obter horários disponíveis para uma data e serviço
 * {@link /websites/booking/slots}
 */
export function useGetBookingSlotsSuspense<TData = GetBookingSlotsQueryResponse, TQueryKey extends QueryKey = GetBookingSlotsSuspenseQueryKey>(params: GetBookingSlotsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetBookingSlotsQueryResponse, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingSlotsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getBookingSlotsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}