/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetBookingServicesQueryResponse, GetBookingServicesQueryParams, GetBookingServices400, GetBookingServices500 } from "../types/GetBookingServices.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getBookingServices } from "../clients/getBookingServices.ts";

export const getBookingServicesSuspenseQueryKey = (params: GetBookingServicesQueryParams) => [{ url: '/websites/booking/services' }, ...(params ? [params] : [])] as const

export type GetBookingServicesSuspenseQueryKey = ReturnType<typeof getBookingServicesSuspenseQueryKey>

export function getBookingServicesSuspenseQueryOptions(params: GetBookingServicesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingServicesSuspenseQueryKey(params)
        return queryOptions<GetBookingServicesQueryResponse, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>, GetBookingServicesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingServices(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Listar serviços activos do prestador
 * {@link /websites/booking/services}
 */
export function useGetBookingServicesSuspense<TData = GetBookingServicesQueryResponse, TQueryKey extends QueryKey = GetBookingServicesSuspenseQueryKey>(params: GetBookingServicesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetBookingServicesQueryResponse, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingServicesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getBookingServicesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}