/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBookingServicesQueryResponse, GetBookingServicesQueryParams, GetBookingServices400, GetBookingServices500 } from "../types/GetBookingServices.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBookingServices } from "../clients/getBookingServices.ts";

export const getBookingServicesQueryKey = (params: GetBookingServicesQueryParams) => [{ url: '/websites/booking/services' }, ...(params ? [params] : [])] as const

export type GetBookingServicesQueryKey = ReturnType<typeof getBookingServicesQueryKey>

export function getBookingServicesQueryOptions(params: GetBookingServicesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBookingServicesQueryKey(params)
        return queryOptions<GetBookingServicesQueryResponse, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>, GetBookingServicesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBookingServices(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Listar serviços activos do prestador
 * {@link /websites/booking/services}
 */
export function useGetBookingServices<TData = GetBookingServicesQueryResponse, TQueryData = GetBookingServicesQueryResponse, TQueryKey extends QueryKey = GetBookingServicesQueryKey>(params: GetBookingServicesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetBookingServicesQueryResponse, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBookingServicesQueryKey(params)
         

         const query = useQuery({
          ...getBookingServicesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}