/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostBookingAppointmentMutationRequest, PostBookingAppointmentMutationResponse, PostBookingAppointment400, PostBookingAppointment404, PostBookingAppointment409, PostBookingAppointment500 } from "../types/PostBookingAppointment.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postBookingAppointment } from "../clients/postBookingAppointment.ts";

export const postBookingAppointmentMutationKey = () => [{ url: '/websites/booking/appointments' }] as const

export type PostBookingAppointmentMutationKey = ReturnType<typeof postBookingAppointmentMutationKey>

export function postBookingAppointmentMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostBookingAppointmentMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postBookingAppointmentMutationKey()
        return mutationOptions<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, {data: PostBookingAppointmentMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postBookingAppointment(data, config)
          },
        })

}

/**
 * @summary Criar nova marcação
 * {@link /websites/booking/appointments}
 */
export function usePostBookingAppointment<TContext>(options: 
{
  mutation?: UseMutationOptions<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, {data: PostBookingAppointmentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostBookingAppointmentMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postBookingAppointmentMutationKey()

          const baseOptions = postBookingAppointmentMutationOptions(config) as UseMutationOptions<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, {data: PostBookingAppointmentMutationRequest}, TContext>
          

          return useMutation<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, {data: PostBookingAppointmentMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, {data: PostBookingAppointmentMutationRequest}, TContext>
      
}