/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PatchBookingAppointmentCancelMutationResponse, PatchBookingAppointmentCancelPathParams, PatchBookingAppointmentCancel400, PatchBookingAppointmentCancel404, PatchBookingAppointmentCancel500 } from "../types/PatchBookingAppointmentCancel.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchBookingAppointmentCancel } from "../clients/patchBookingAppointmentCancel.ts";

export const patchBookingAppointmentCancelMutationKey = () => [{ url: '/websites/booking/appointments/:cancelToken/cancel' }] as const

export type PatchBookingAppointmentCancelMutationKey = ReturnType<typeof patchBookingAppointmentCancelMutationKey>

export function patchBookingAppointmentCancelMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = patchBookingAppointmentCancelMutationKey()
        return mutationOptions<PatchBookingAppointmentCancelMutationResponse, ResponseErrorConfig<PatchBookingAppointmentCancel400 | PatchBookingAppointmentCancel404 | PatchBookingAppointmentCancel500>, {cancelToken: PatchBookingAppointmentCancelPathParams["cancelToken"]}, TContext>({
          mutationKey,
          mutationFn: async({ cancelToken }) => {
            return patchBookingAppointmentCancel(cancelToken, config)
          },
        })

}

/**
 * @summary Cancelar uma marcação
 * {@link /websites/booking/appointments/:cancelToken/cancel}
 */
export function usePatchBookingAppointmentCancel<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchBookingAppointmentCancelMutationResponse, ResponseErrorConfig<PatchBookingAppointmentCancel400 | PatchBookingAppointmentCancel404 | PatchBookingAppointmentCancel500>, {cancelToken: PatchBookingAppointmentCancelPathParams["cancelToken"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? patchBookingAppointmentCancelMutationKey()

          const baseOptions = patchBookingAppointmentCancelMutationOptions(config) as UseMutationOptions<PatchBookingAppointmentCancelMutationResponse, ResponseErrorConfig<PatchBookingAppointmentCancel400 | PatchBookingAppointmentCancel404 | PatchBookingAppointmentCancel500>, {cancelToken: PatchBookingAppointmentCancelPathParams["cancelToken"]}, TContext>
          

          return useMutation<PatchBookingAppointmentCancelMutationResponse, ResponseErrorConfig<PatchBookingAppointmentCancel400 | PatchBookingAppointmentCancel404 | PatchBookingAppointmentCancel500>, {cancelToken: PatchBookingAppointmentCancelPathParams["cancelToken"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PatchBookingAppointmentCancelMutationResponse, ResponseErrorConfig<PatchBookingAppointmentCancel400 | PatchBookingAppointmentCancel404 | PatchBookingAppointmentCancel500>, {cancelToken: PatchBookingAppointmentCancelPathParams["cancelToken"]}, TContext>
      
}