/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Service } from "./Service.ts";

export type GetBookingServicesQueryParams = {
    /**
     * @description ID do prestador de serviço no sistema
     * @type string, uuid
    */
    userId: string;
};

/**
 * @description Lista de serviços activos
*/
export type GetBookingServices200 = Service[];

/**
 * @description userId obrigatório
*/
export type GetBookingServices400 = any;

/**
 * @description Erro interno
*/
export type GetBookingServices500 = any;

export type GetBookingServicesQueryResponse = GetBookingServices200;

export type GetBookingServicesQuery = {
    Response: GetBookingServices200;
    QueryParams: GetBookingServicesQueryParams;
    Errors: GetBookingServices400 | GetBookingServices500;
};