/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetBookingMyAppointmentsQueryResponse, GetBookingMyAppointmentsQueryParams, GetBookingMyAppointments401, GetBookingMyAppointments403, GetBookingMyAppointments404, GetBookingMyAppointments500 } from "../types/GetBookingMyAppointments.ts";

function getGetBookingMyAppointmentsUrl() {
  const res = { method: 'GET', url: `/websites/booking/my-appointments` as const }
  return res
}

/**
 * @summary Marcações do cliente autenticado neste prestador
 * {@link /websites/booking/my-appointments}
 */
export async function getBookingMyAppointments(params?: GetBookingMyAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetBookingMyAppointmentsQueryResponse, ResponseErrorConfig<GetBookingMyAppointments401 | GetBookingMyAppointments403 | GetBookingMyAppointments404 | GetBookingMyAppointments500>, unknown>({ method : "GET", url : getGetBookingMyAppointmentsUrl().url.toString(), params, ... requestConfig })
  return res.data
}