/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetBookingServicesQueryResponse, GetBookingServicesQueryParams, GetBookingServices400, GetBookingServices500 } from "../types/GetBookingServices.ts";

function getGetBookingServicesUrl() {
  const res = { method: 'GET', url: `/websites/booking/services` as const }
  return res
}

/**
 * @summary Listar serviços activos do prestador
 * {@link /websites/booking/services}
 */
export async function getBookingServices(params: GetBookingServicesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetBookingServicesQueryResponse, ResponseErrorConfig<GetBookingServices400 | GetBookingServices500>, unknown>({ method : "GET", url : getGetBookingServicesUrl().url.toString(), params, ... requestConfig })
  return res.data
}