/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetBookingSlotsQueryResponse, GetBookingSlotsQueryParams, GetBookingSlots400, GetBookingSlots404, GetBookingSlots500 } from "../types/GetBookingSlots.ts";

function getGetBookingSlotsUrl() {
  const res = { method: 'GET', url: `/websites/booking/slots` as const }
  return res
}

/**
 * @summary Obter horários disponíveis para uma data e serviço
 * {@link /websites/booking/slots}
 */
export async function getBookingSlots(params: GetBookingSlotsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetBookingSlotsQueryResponse, ResponseErrorConfig<GetBookingSlots400 | GetBookingSlots404 | GetBookingSlots500>, unknown>({ method : "GET", url : getGetBookingSlotsUrl().url.toString(), params, ... requestConfig })
  return res.data
}