/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { PostBookingAppointmentMutationRequest, PostBookingAppointmentMutationResponse, PostBookingAppointment400, PostBookingAppointment404, PostBookingAppointment409, PostBookingAppointment500 } from "../types/PostBookingAppointment.ts";

function getPostBookingAppointmentUrl() {
  const res = { method: 'POST', url: `/websites/booking/appointments` as const }
  return res
}

/**
 * @summary Criar nova marcação
 * {@link /websites/booking/appointments}
 */
export async function postBookingAppointment(data: PostBookingAppointmentMutationRequest, config: Partial<RequestConfig<PostBookingAppointmentMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostBookingAppointmentMutationResponse, ResponseErrorConfig<PostBookingAppointment400 | PostBookingAppointment404 | PostBookingAppointment409 | PostBookingAppointment500>, PostBookingAppointmentMutationRequest>({ method : "POST", url : getPostBookingAppointmentUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}